version: 2
jobs:
  build:
   working_directory: ~/analytics-android-integration-adobe-analytics
   docker:
     - image: circleci/android:api-26-alpha
   environment:
     JVM_OPTS: -Xmx3200m
     CIRCLE_JDK_VERSION: oraclejdk8
   steps:
     - checkout
     - restore_cache:
         key: jars-{{ checksum "build.gradle" }}
     - run:
         name: Build
         command: ./gradlew checkFmt build
     - save_cache:
         paths:
           - ~/.gradle
         key: jars-{{ checksum "build.gradle" }}
     - run:
         name: Upload code coverage reports
         command: bash <(curl -s https://codecov.io/bash)
     - run:
         name: Deployment
         command: |
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
             .buildscript/deploy_snapshot.sh
           else
             echo "==> ignoring non-master branch"
           fi